apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tyk-azure-keyvault
  namespace: tyk
spec:
  provider: azure
  secretObjects:
  # PostgreSQL secrets
  - secretName: tyk-postgres-secret
    type: Opaque
    data:
    - objectName: postgres-host
      key: postgres-host
    - objectName: postgres-user
      key: postgres-user
    - objectName: postgres-password
      key: postgres-password
    - objectName: postgres-database
      key: postgres-database
    - objectName: postgres-connection-string
      key: postgres-connection-string
  
  # Redis secrets
  - secretName: tyk-redis-secret
    type: Opaque
    data:
    - objectName: redis-host
      key: redis-host
    - objectName: redis-port
      key: redis-port
    - objectName: redis-password
      key: redis-password
    - objectName: redis-addrs
      key: redis-addrs
  
  # Main Tyk secrets (licenses and API secrets)
  - secretName: tyk-secrets
    type: Opaque
    data:
    - objectName: dashboard-license
      key: DashLicense
    - objectName: operator-license
      key: OperatorLicense
    - objectName: api-secret
      key: APISecret
    - objectName: admin-secret
      key: AdminSecret
  
  # MDCB secrets
  - secretName: tyk-mdcb-secret
    type: Opaque
    data:
    - objectName: mdcb-license
      key: MDCBLicense
    - objectName: mdcb-security-secret
      key: securitySecret
  
  # Admin user secrets
  - secretName: tyk-admin-user-secret
    type: Opaque
    data:
    - objectName: admin-user-first-name
      key: adminUserFirstName
    - objectName: admin-user-last-name
      key: adminUserLastName
    - objectName: admin-user-email
      key: adminUserEmail
    - objectName: admin-user-password
      key: adminUserPassword
  
  # Developer Portal secrets (if available)
  - secretName: tyk-dev-portal-secret
    type: Opaque
    data:
    - objectName: portal-license
      key: DevPortalLicense
    - objectName: postgres-connection-string
      key: DevPortalDatabaseConnectionString
  
  # Developer Portal bootstrap secrets (used by Helm chart)
  - secretName: secrets-tyk-cp-tyk-dev-portal
    type: Opaque
    data:
    - objectName: admin-user-password
      key: adminUserPassword

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "tyk-control-plane-dev-kv"
    tenantId: "05a79b34-cba0-41a6-b4be-5c7147468908"
    objects: |
      array:
        - |
          objectName: postgres-host
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-database
          objectType: secret
        - |
          objectName: postgres-connection-string
          objectType: secret
        - |
          objectName: redis-host
          objectType: secret
        - |
          objectName: redis-port
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: redis-addrs
          objectType: secret
        - |
          objectName: dashboard-license
          objectType: secret
        - |
          objectName: mdcb-license
          objectType: secret
        - |
          objectName: mdcb-security-secret
          objectType: secret
        - |
          objectName: portal-license
          objectType: secret
        - |
          objectName: operator-license
          objectType: secret
        - |
          objectName: api-secret
          objectType: secret
        - |
          objectName: admin-secret
          objectType: secret
        - |
          objectName: admin-user-first-name
          objectType: secret
        - |
          objectName: admin-user-last-name
          objectType: secret
        - |
          objectName: admin-user-email
          objectType: secret
        - |
          objectName: admin-user-password
          objectType: secret