# Tyk Control Plane GitOps Values
# This file contains the Helm values for deploying Tyk Control Plane via ArgoCD
# Secrets are referenced via secretKeyRef and must be created beforehand

global:
  # Storage configuration
  storageType: postgres
  
  # PostgreSQL Configuration (references infrastructure secrets)
  postgres:
    host:
      valueFrom:
        secretKeyRef:
          name: tyk-infrastructure-secret
          key: postgresHost
    port: 5432
    user:
      valueFrom:
        secretKeyRef:
          name: tyk-infrastructure-secret
          key: postgresUser
    password:
      valueFrom:
        secretKeyRef:
          name: tyk-infrastructure-secret
          key: postgresPassword
    database:
      valueFrom:
        secretKeyRef:
          name: tyk-infrastructure-secret
          key: postgresDatabase
    sslmode: require

  # Redis Configuration (references infrastructure secrets)
  redis:
    addrs:
      - valueFrom:
          secretKeyRef:
            name: tyk-infrastructure-secret
            key: redisHost
    passSecret:
      name: tyk-infrastructure-secret
      keyName: redisPassword
    enableCluster: false
    useSSL: true

  # Use existing secrets for all Tyk configurations
  secrets:
    useSecretName: "tyk-control-plane-secret"
  
  # Admin user configuration
  adminUser:
    useSecretName: "tyk-control-plane-secret"

  # Component Enablement
  components:
    bootstrap: true
    dashboard: true
    gateway: true
    pump: true
    mdcb: true
    devPortal: true
    operator: true

# Tyk Gateway Configuration
tyk-gateway:
  gateway:
    image:
      tag: v5.8.1
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Tyk Dashboard Configuration
tyk-dashboard:
  dashboard:
    image:
      tag: v5.8.1
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: false
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

# Tyk MDCB Configuration
tyk-mdcb:
  mdcb:
    image:
      tag: v2.8.1
    service:
      type: ClusterIP
      port: 9091
    ingress:
      enabled: false
    useSecretName: "tyk-control-plane-secret"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Tyk Pump Configuration
tyk-pump:
  pump:
    image:
      tag: v1.12.0
    backend:
      - "postgres"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Enterprise Developer Portal Configuration
tyk-dev-portal:
  enabled: true
  image:
    tag: v1.13.2
  service:
    type: ClusterIP
    port: 3001
  ingress:
    enabled: false
  useSecretName: "tyk-control-plane-secret"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Tyk Operator Configuration
tyk-operator:
  image:
    tag: v1.2.0
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# External services (disabled)
redis:
  enabled: false

postgresql:
  enabled: false