# Tyk Control Plane GitOps Values
# This file contains the Helm values for deploying Tyk Control Plane via ArgoCD
# Secrets are referenced via secretKeyRef and must be created beforehand

global:
  # PostgreSQL Configuration (references existing secrets)
  postgres:
    host: 
      secretKeyRef:
        name: tyk-postgres-secret
        key: host
    port: 5432
    user: 
      secretKeyRef:
        name: tyk-postgres-secret
        key: user
    password: 
      secretKeyRef:
        name: tyk-postgres-secret
        key: password
    database: 
      secretKeyRef:
        name: tyk-postgres-secret
        key: database
    sslmode: require

  # Redis Configuration (references existing secrets)
  redis:
    addrs:
      - secretKeyRef:
          name: tyk-redis-secret
          key: addr
    pass: 
      secretKeyRef:
        name: tyk-redis-secret
        key: password
    enableCluster: false
    useSSL: true

  # Tyk License Configuration (references existing secrets)
  license:
    dashboard: 
      secretKeyRef:
        name: tyk-license-secret
        key: dashboard
    mdcb: 
      secretKeyRef:
        name: tyk-license-secret
        key: mdcb
    operator: 
      secretKeyRef:
        name: tyk-license-secret
        key: operator
    
  # Enterprise Developer Portal License
  enterprisePortal:
    license: 
      secretKeyRef:
        name: tyk-license-secret
        key: portal

  # Security Configuration (references existing secrets)
  secrets:
    APISecret: 
      secretKeyRef:
        name: tyk-security-secret
        key: api-secret
    AdminSecret: 
      secretKeyRef:
        name: tyk-security-secret
        key: admin-secret

  # Global Admin User Configuration (references existing secrets)
  adminUser:
    firstName: 
      secretKeyRef:
        name: tyk-admin-secret
        key: first-name
    lastName: 
      secretKeyRef:
        name: tyk-admin-secret
        key: last-name
    email: 
      secretKeyRef:
        name: tyk-admin-secret
        key: email
    password: 
      secretKeyRef:
        name: tyk-admin-secret
        key: password

  # Component Enablement
  components:
    bootstrap: true
    dashboard: true
    gateway: true
    pump: true
    mdcb: true
    devPortal: true
    operator: true

# Tyk Gateway Configuration
tyk-gateway:
  gateway:
    image:
      tag: v5.8.1
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Tyk Dashboard Configuration
tyk-dashboard:
  dashboard:
    image:
      tag: v5.8.1
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: false
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

# Tyk MDCB Configuration
tyk-mdcb:
  mdcb:
    image:
      tag: v2.8.1
    service:
      type: ClusterIP
      port: 9091
    ingress:
      enabled: false
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Tyk Pump Configuration
tyk-pump:
  pump:
    image:
      tag: v1.12.0
    backend:
      - "postgres"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Enterprise Developer Portal Configuration
tyk-dev-portal:
  enabled: true
  image:
    tag: v1.13.2
  service:
    type: ClusterIP
    port: 3001
  ingress:
    enabled: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Tyk Operator Configuration
tyk-operator:
  image:
    tag: v1.2.0
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# External services (disabled)
redis:
  enabled: false

postgresql:
  enabled: false