apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-control-plane-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TykTechnologies/tyk-ops
    targetRevision: HEAD
    path: gitops/applications
    directory:
      recurse: false
      exclude: 'root-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: 'Description'
      value: 'Root application managing Tyk Control Plane GitOps deployment'
    - name: 'Components'
      value: 'Prerequisites and Control Plane applications'