apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TykTechnologies/tyk-ops.git
    targetRevision: HEAD
    path: gitops/tyk-control-plane
    helm:
      releaseName: tyk-cp
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: 'Description'
      value: 'Tyk Control Plane - GitOps deployment via ArgoCD using Chart.yaml'
    - name: 'Prerequisites'
      value: 'Requires infrastructure.env and .env secrets, and cert-manager'
    - name: 'Components'
      value: 'Gateway v5.8.1, Dashboard v5.8.1, MDCB v2.8.1, Pump, Bootstrap'
    - name: 'Secret Management'
      value: 'Uses Helm chart built-in secret references'