apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: tyk-control-plane
    repoURL: https://helm.tyk.io/public/helm/charts/
    targetRevision: 3.0.0
    helm:
      releaseName: tyk-cp
      valuesObject:
        global:
          storageType: postgres
          secrets:
            useSecretName: "tyk-control-plane-secret"
          adminUser:
            useSecretName: "tyk-control-plane-secret"
          postgres:
            host:
              valueFrom:
                secretKeyRef:
                  name: tyk-infrastructure-secret
                  key: postgresHost
            port: 5432
            user:
              valueFrom:
                secretKeyRef:
                  name: tyk-infrastructure-secret
                  key: postgresUser
            password:
              valueFrom:
                secretKeyRef:
                  name: tyk-infrastructure-secret
                  key: postgresPassword
            database:
              valueFrom:
                secretKeyRef:
                  name: tyk-infrastructure-secret
                  key: postgresDatabase
            sslmode: require
          redis:
            passSecret:
              name: tyk-infrastructure-secret
              keyName: redisPassword
            addrs:
              - valueFrom:
                  secretKeyRef:
                    name: tyk-infrastructure-secret
                    key: redisHost
            enableCluster: false
            useSSL: true
          components:
            bootstrap: true
            dashboard: true
            gateway: true
            pump: true
            mdcb: true
            devPortal: true
            operator: true
        tyk-gateway:
          gateway:
            image:
              tag: v5.8.1
            service:
              type: ClusterIP
              port: 8080
            ingress:
              enabled: false
        tyk-dashboard:
          dashboard:
            image:
              tag: v5.8.1
            service:
              type: ClusterIP
              port: 3000
            ingress:
              enabled: false
          useSecretName: "tyk-control-plane-secret"
        tyk-mdcb:
          mdcb:
            image:
              tag: v2.8.1
            service:
              type: ClusterIP
              port: 9091
            ingress:
              enabled: false
            useSecretName: "tyk-control-plane-secret"
        tyk-dev-portal:
          enabled: true
          image:
            tag: v1.13.2
          service:
            type: ClusterIP
            port: 3001
          ingress:
            enabled: false
          useSecretName: "tyk-control-plane-secret"
        tyk-operator:
          image:
            tag: v1.2.0
        redis:
          enabled: false
        postgresql:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  info:
    - name: 'Description'
      value: 'Tyk Control Plane - GitOps deployment via ArgoCD'
    - name: 'Prerequisites'
      value: 'Requires infrastructure.env and .env secrets, and cert-manager'
    - name: 'Components'
      value: 'Gateway v5.8.1, Dashboard v5.8.1, MDCB v2.8.1, Pump, Portal, Operator'