# Tyk Operator CRDs - Applied directly via ArgoCD
# These CRDs will be fetched from the Tyk repository
apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  install-script: |
    #!/bin/bash
    set -e
    echo "Installing Tyk Operator CRDs v1.2.0..."
    kubectl apply -f https://raw.githubusercontent.com/TykTechnologies/tyk-charts/refs/heads/main/tyk-operator-crds/crd-v1.2.0.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-tyk-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: argocd-application-controller
      containers:
      - name: install-crds
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing Tyk Operator CRDs..."
          if kubectl get crd apidefinitions.tyk.tyk.io &> /dev/null; then
            echo "CRDs already installed"
            exit 0
          fi
          kubectl apply -f https://raw.githubusercontent.com/TykTechnologies/tyk-charts/refs/heads/main/tyk-operator-crds/crd-v1.2.0.yaml
          echo "CRDs installation complete"